// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// HTTPRequestsColumns holds the columns for the "http_requests" table.
	HTTPRequestsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "received", Type: field.TypeTime},
		{Name: "host", Type: field.TypeString},
		{Name: "path", Type: field.TypeString},
		{Name: "method", Type: field.TypeString},
		{Name: "header", Type: field.TypeJSON},
		{Name: "body", Type: field.TypeBytes},
	}
	// HTTPRequestsTable holds the schema information for the "http_requests" table.
	HTTPRequestsTable = &schema.Table{
		Name:       "http_requests",
		Columns:    HTTPRequestsColumns,
		PrimaryKey: []*schema.Column{HTTPRequestsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		HTTPRequestsTable,
	}
)

func init() {
}
