// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mark-ignacio/http2sqlite/ent/httprequest"
	"github.com/mark-ignacio/http2sqlite/ent/predicate"
)

// HTTPRequestQuery is the builder for querying HTTPRequest entities.
type HTTPRequestQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.HTTPRequest
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the HTTPRequestQuery builder.
func (hrq *HTTPRequestQuery) Where(ps ...predicate.HTTPRequest) *HTTPRequestQuery {
	hrq.predicates = append(hrq.predicates, ps...)
	return hrq
}

// Limit adds a limit step to the query.
func (hrq *HTTPRequestQuery) Limit(limit int) *HTTPRequestQuery {
	hrq.limit = &limit
	return hrq
}

// Offset adds an offset step to the query.
func (hrq *HTTPRequestQuery) Offset(offset int) *HTTPRequestQuery {
	hrq.offset = &offset
	return hrq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (hrq *HTTPRequestQuery) Unique(unique bool) *HTTPRequestQuery {
	hrq.unique = &unique
	return hrq
}

// Order adds an order step to the query.
func (hrq *HTTPRequestQuery) Order(o ...OrderFunc) *HTTPRequestQuery {
	hrq.order = append(hrq.order, o...)
	return hrq
}

// First returns the first HTTPRequest entity from the query.
// Returns a *NotFoundError when no HTTPRequest was found.
func (hrq *HTTPRequestQuery) First(ctx context.Context) (*HTTPRequest, error) {
	nodes, err := hrq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{httprequest.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (hrq *HTTPRequestQuery) FirstX(ctx context.Context) *HTTPRequest {
	node, err := hrq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first HTTPRequest ID from the query.
// Returns a *NotFoundError when no HTTPRequest ID was found.
func (hrq *HTTPRequestQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = hrq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{httprequest.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (hrq *HTTPRequestQuery) FirstIDX(ctx context.Context) int {
	id, err := hrq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single HTTPRequest entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one HTTPRequest entity is not found.
// Returns a *NotFoundError when no HTTPRequest entities are found.
func (hrq *HTTPRequestQuery) Only(ctx context.Context) (*HTTPRequest, error) {
	nodes, err := hrq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{httprequest.Label}
	default:
		return nil, &NotSingularError{httprequest.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (hrq *HTTPRequestQuery) OnlyX(ctx context.Context) *HTTPRequest {
	node, err := hrq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only HTTPRequest ID in the query.
// Returns a *NotSingularError when exactly one HTTPRequest ID is not found.
// Returns a *NotFoundError when no entities are found.
func (hrq *HTTPRequestQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = hrq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{httprequest.Label}
	default:
		err = &NotSingularError{httprequest.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (hrq *HTTPRequestQuery) OnlyIDX(ctx context.Context) int {
	id, err := hrq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of HTTPRequests.
func (hrq *HTTPRequestQuery) All(ctx context.Context) ([]*HTTPRequest, error) {
	if err := hrq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return hrq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (hrq *HTTPRequestQuery) AllX(ctx context.Context) []*HTTPRequest {
	nodes, err := hrq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of HTTPRequest IDs.
func (hrq *HTTPRequestQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := hrq.Select(httprequest.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (hrq *HTTPRequestQuery) IDsX(ctx context.Context) []int {
	ids, err := hrq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (hrq *HTTPRequestQuery) Count(ctx context.Context) (int, error) {
	if err := hrq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return hrq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (hrq *HTTPRequestQuery) CountX(ctx context.Context) int {
	count, err := hrq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (hrq *HTTPRequestQuery) Exist(ctx context.Context) (bool, error) {
	if err := hrq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return hrq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (hrq *HTTPRequestQuery) ExistX(ctx context.Context) bool {
	exist, err := hrq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the HTTPRequestQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (hrq *HTTPRequestQuery) Clone() *HTTPRequestQuery {
	if hrq == nil {
		return nil
	}
	return &HTTPRequestQuery{
		config:     hrq.config,
		limit:      hrq.limit,
		offset:     hrq.offset,
		order:      append([]OrderFunc{}, hrq.order...),
		predicates: append([]predicate.HTTPRequest{}, hrq.predicates...),
		// clone intermediate query.
		sql:  hrq.sql.Clone(),
		path: hrq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Received time.Time `json:"received,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.HTTPRequest.Query().
//		GroupBy(httprequest.FieldReceived).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (hrq *HTTPRequestQuery) GroupBy(field string, fields ...string) *HTTPRequestGroupBy {
	group := &HTTPRequestGroupBy{config: hrq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := hrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return hrq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Received time.Time `json:"received,omitempty"`
//	}
//
//	client.HTTPRequest.Query().
//		Select(httprequest.FieldReceived).
//		Scan(ctx, &v)
//
func (hrq *HTTPRequestQuery) Select(fields ...string) *HTTPRequestSelect {
	hrq.fields = append(hrq.fields, fields...)
	return &HTTPRequestSelect{HTTPRequestQuery: hrq}
}

func (hrq *HTTPRequestQuery) prepareQuery(ctx context.Context) error {
	for _, f := range hrq.fields {
		if !httprequest.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if hrq.path != nil {
		prev, err := hrq.path(ctx)
		if err != nil {
			return err
		}
		hrq.sql = prev
	}
	return nil
}

func (hrq *HTTPRequestQuery) sqlAll(ctx context.Context) ([]*HTTPRequest, error) {
	var (
		nodes = []*HTTPRequest{}
		_spec = hrq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &HTTPRequest{config: hrq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, hrq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (hrq *HTTPRequestQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := hrq.querySpec()
	_spec.Node.Columns = hrq.fields
	if len(hrq.fields) > 0 {
		_spec.Unique = hrq.unique != nil && *hrq.unique
	}
	return sqlgraph.CountNodes(ctx, hrq.driver, _spec)
}

func (hrq *HTTPRequestQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := hrq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (hrq *HTTPRequestQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   httprequest.Table,
			Columns: httprequest.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: httprequest.FieldID,
			},
		},
		From:   hrq.sql,
		Unique: true,
	}
	if unique := hrq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := hrq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, httprequest.FieldID)
		for i := range fields {
			if fields[i] != httprequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := hrq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := hrq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := hrq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := hrq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (hrq *HTTPRequestQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(hrq.driver.Dialect())
	t1 := builder.Table(httprequest.Table)
	columns := hrq.fields
	if len(columns) == 0 {
		columns = httprequest.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if hrq.sql != nil {
		selector = hrq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if hrq.unique != nil && *hrq.unique {
		selector.Distinct()
	}
	for _, p := range hrq.predicates {
		p(selector)
	}
	for _, p := range hrq.order {
		p(selector)
	}
	if offset := hrq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := hrq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// HTTPRequestGroupBy is the group-by builder for HTTPRequest entities.
type HTTPRequestGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (hrgb *HTTPRequestGroupBy) Aggregate(fns ...AggregateFunc) *HTTPRequestGroupBy {
	hrgb.fns = append(hrgb.fns, fns...)
	return hrgb
}

// Scan applies the group-by query and scans the result into the given value.
func (hrgb *HTTPRequestGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := hrgb.path(ctx)
	if err != nil {
		return err
	}
	hrgb.sql = query
	return hrgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (hrgb *HTTPRequestGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := hrgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (hrgb *HTTPRequestGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(hrgb.fields) > 1 {
		return nil, errors.New("ent: HTTPRequestGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := hrgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (hrgb *HTTPRequestGroupBy) StringsX(ctx context.Context) []string {
	v, err := hrgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (hrgb *HTTPRequestGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = hrgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{httprequest.Label}
	default:
		err = fmt.Errorf("ent: HTTPRequestGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (hrgb *HTTPRequestGroupBy) StringX(ctx context.Context) string {
	v, err := hrgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (hrgb *HTTPRequestGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(hrgb.fields) > 1 {
		return nil, errors.New("ent: HTTPRequestGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := hrgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (hrgb *HTTPRequestGroupBy) IntsX(ctx context.Context) []int {
	v, err := hrgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (hrgb *HTTPRequestGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = hrgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{httprequest.Label}
	default:
		err = fmt.Errorf("ent: HTTPRequestGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (hrgb *HTTPRequestGroupBy) IntX(ctx context.Context) int {
	v, err := hrgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (hrgb *HTTPRequestGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(hrgb.fields) > 1 {
		return nil, errors.New("ent: HTTPRequestGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := hrgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (hrgb *HTTPRequestGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := hrgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (hrgb *HTTPRequestGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = hrgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{httprequest.Label}
	default:
		err = fmt.Errorf("ent: HTTPRequestGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (hrgb *HTTPRequestGroupBy) Float64X(ctx context.Context) float64 {
	v, err := hrgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (hrgb *HTTPRequestGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(hrgb.fields) > 1 {
		return nil, errors.New("ent: HTTPRequestGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := hrgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (hrgb *HTTPRequestGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := hrgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (hrgb *HTTPRequestGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = hrgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{httprequest.Label}
	default:
		err = fmt.Errorf("ent: HTTPRequestGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (hrgb *HTTPRequestGroupBy) BoolX(ctx context.Context) bool {
	v, err := hrgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (hrgb *HTTPRequestGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range hrgb.fields {
		if !httprequest.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := hrgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := hrgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (hrgb *HTTPRequestGroupBy) sqlQuery() *sql.Selector {
	selector := hrgb.sql.Select()
	aggregation := make([]string, 0, len(hrgb.fns))
	for _, fn := range hrgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(hrgb.fields)+len(hrgb.fns))
		for _, f := range hrgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(hrgb.fields...)...)
}

// HTTPRequestSelect is the builder for selecting fields of HTTPRequest entities.
type HTTPRequestSelect struct {
	*HTTPRequestQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (hrs *HTTPRequestSelect) Scan(ctx context.Context, v interface{}) error {
	if err := hrs.prepareQuery(ctx); err != nil {
		return err
	}
	hrs.sql = hrs.HTTPRequestQuery.sqlQuery(ctx)
	return hrs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (hrs *HTTPRequestSelect) ScanX(ctx context.Context, v interface{}) {
	if err := hrs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (hrs *HTTPRequestSelect) Strings(ctx context.Context) ([]string, error) {
	if len(hrs.fields) > 1 {
		return nil, errors.New("ent: HTTPRequestSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := hrs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (hrs *HTTPRequestSelect) StringsX(ctx context.Context) []string {
	v, err := hrs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (hrs *HTTPRequestSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = hrs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{httprequest.Label}
	default:
		err = fmt.Errorf("ent: HTTPRequestSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (hrs *HTTPRequestSelect) StringX(ctx context.Context) string {
	v, err := hrs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (hrs *HTTPRequestSelect) Ints(ctx context.Context) ([]int, error) {
	if len(hrs.fields) > 1 {
		return nil, errors.New("ent: HTTPRequestSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := hrs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (hrs *HTTPRequestSelect) IntsX(ctx context.Context) []int {
	v, err := hrs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (hrs *HTTPRequestSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = hrs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{httprequest.Label}
	default:
		err = fmt.Errorf("ent: HTTPRequestSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (hrs *HTTPRequestSelect) IntX(ctx context.Context) int {
	v, err := hrs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (hrs *HTTPRequestSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(hrs.fields) > 1 {
		return nil, errors.New("ent: HTTPRequestSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := hrs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (hrs *HTTPRequestSelect) Float64sX(ctx context.Context) []float64 {
	v, err := hrs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (hrs *HTTPRequestSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = hrs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{httprequest.Label}
	default:
		err = fmt.Errorf("ent: HTTPRequestSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (hrs *HTTPRequestSelect) Float64X(ctx context.Context) float64 {
	v, err := hrs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (hrs *HTTPRequestSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(hrs.fields) > 1 {
		return nil, errors.New("ent: HTTPRequestSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := hrs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (hrs *HTTPRequestSelect) BoolsX(ctx context.Context) []bool {
	v, err := hrs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (hrs *HTTPRequestSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = hrs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{httprequest.Label}
	default:
		err = fmt.Errorf("ent: HTTPRequestSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (hrs *HTTPRequestSelect) BoolX(ctx context.Context) bool {
	v, err := hrs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (hrs *HTTPRequestSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := hrs.sql.Query()
	if err := hrs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
