// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/mark-ignacio/http2sqlite/ent/httprequest"
	"github.com/mark-ignacio/http2sqlite/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	httprequestFields := schema.HTTPRequest{}.Fields()
	_ = httprequestFields
	// httprequestDescReceived is the schema descriptor for received field.
	httprequestDescReceived := httprequestFields[0].Descriptor()
	// httprequest.DefaultReceived holds the default value on creation for the received field.
	httprequest.DefaultReceived = httprequestDescReceived.Default.(func() time.Time)
}
