on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker build
        run: |
          docker build . \
            -t ghcr.io/mark-ignacio/http2sqlite:latest \
            -t ghcr.io/mark-ignacio/http2sqlite:${{ github.sha }}
        env:
          DOCKER_BUILDKIT: 1
      - name: docker push
        run: |
          docker push ghcr.io/mark-ignacio/http2sqlite:latest
          docker push ghcr.io/mark-ignacio/http2sqlite:${{ github.sha }}
