// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// HTTPRequest is the predicate function for httprequest builders.
type HTTPRequest func(*sql.Selector)
